# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: default

    files:
      - LICENSE.md
      - README.md
      - _source-awsp.sh
      - awsp.ps1

    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format: tar.gz

    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: awsp
    homepage: https://github.com/abyss/go-awsp
    description: "Easily switch between AWS Profiles with an interactive selector"

    directory: Formula
    repository:
      owner: abyss
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TOOLS_PAT }}"

    install: |
      prefix.install "_source-awsp.sh"
      bin.install "go-awsp"

    caveats: |
      ##################################################################

      To use awsp, add the following to your shell profile:
          alias awsp='source "$(brew --prefix awsp)/_source-awsp.sh"'

      ##################################################################
